{
    "login": "adion81",
    "id": 43325621,
    "node_id": "MDQ6VXNlcjQzMzI1NjIx",
    "avatar_url": "https://avatars.githubusercontent.com/u/43325621?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adion81",
    "html_url": "https://github.com/adion81",
    "followers_url": "https://api.github.com/users/adion81/followers",
    "following_url": "https://api.github.com/users/adion81/following{/other_user}",
    "gists_url": "https://api.github.com/users/adion81/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adion81/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adion81/subscriptions",
    "organizations_url": "https://api.github.com/users/adion81/orgs",
    "repos_url": "https://api.github.com/users/adion81/repos",
    "events_url": "https://api.github.com/users/adion81/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adion81/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Adrien Dion",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 126,
    "public_gists": 0,
    "followers": 80,
    "following": 11,
    "created_at": "2018-09-16T23:29:16Z",
    "updated_at": "2023-08-09T21:01:17Z"
  }